apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-afci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-afci
    app.kubernetes.io/part-of: hacbs-demo-test-app-fobv
  name: test-component-afci
  namespace: hacbs-e2e-aspk
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-afci
status:
  loadBalancer: {}
